[package]
name = "garive-tui"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
clap.workspace = true
garive-host-client = { path = "../clients/host-rs" }
tokio.workspace = true

[[bin]]
name = "garive-tui"
path = "src/main.rs"
