import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const CSS = readFileSync(fileURLToPath(new URL("./style.css", import.meta.url)), "utf8");
const TOKENS = readFileSync(fileURLToPath(new URL("./visual-system.css", import.meta.url)), "utf8");

describe("Desktop visual accessibility contract", () => {
  it("retains explicit focus, motion, transparency, contrast and forced-color modes", () => {
    for (const contract of [":focus-visible", "prefers-reduced-motion: reduce",
      "prefers-reduced-transparency: reduce", "prefers-contrast: more", "forced-colors: active"]) {
      expect(CSS).toContain(contract);
    }
  });

  it("reflows the complete work surface at the 320 CSS pixel boundary", () => {
    const narrow = media("max-width: 480px");
    expect(narrow).toContain("grid-template-columns: minmax(0, 1fr)");
    expect(narrow).toContain(".sidebar { display: none; }");
    expect(narrow).toContain(".main-surface, .topbar, .work-surface, .conversation, .composer-wrap, .composer, .timeline { min-width: 0; max-width: 100%; }");
    expect(narrow).toContain(".approval-foot { flex-direction: column; align-items: stretch; }");
    expect(narrow).toContain(".approval-actions { align-self: flex-end; }");
    expect(CSS).toContain(".app-shell, .app-shell:has(.environment-panel), .app-shell:has(.workspace-panel) { grid-template-columns: minmax(0, 1fr); }");
    expect(CSS).toContain(".app-shell, .app-shell:has(.environment-panel), .app-shell:has(.workspace-panel) { grid-template-columns: 72px minmax(0, 1fr); }");
    expect(CSS).toContain("flex-basis: auto; width: min(300px, calc(100% - 48px)); max-width: min(300px, calc(100% - 48px));");
    expect(CSS).toContain("padding: 18px 10px 12px; overflow: hidden;");
  });

  it("keeps normal semantic text tokens at WCAG AA contrast in light and dark", () => {
    expect(contrast("5f5f5f", "ffffff")).toBeGreaterThanOrEqual(4.5);
    expect(contrast("707070", "ffffff")).toBeGreaterThanOrEqual(4.5);
    expect(contrast("bababa", "181818")).toBeGreaterThanOrEqual(4.5);
    expect(contrast("8c8c8c", "181818")).toBeGreaterThanOrEqual(4.5);
    expect(contrast("dfdfdf", "292a27")).toBeGreaterThanOrEqual(4.5);
  });

  it("freezes the shared Codex-fidelity scale and wide shell geometry", () => {
    for (const token of ["--text-2xs: 11px", "--text-xs: 12px", "--text-sm: 13px",
      "--surface-canvas: #ffffff", "--surface-sidebar: #f7f7f7",
      "--surface-canvas: #181818", "--surface-sidebar: #2b2527"]) {
      expect(TOKENS).toContain(token);
    }
    expect(TOKENS).toContain("--document-font-size: 13px");
    expect(TOKENS).toContain("--document-leading: 1.625");
    expect(TOKENS).toContain("--conversation-item-gap: 16px");
    expect(TOKENS).toContain("--conversation-grouped-item-gap: 4px");
    expect(TOKENS).toContain("--user-chat-width: 70%");
    expect(TOKENS).toContain("--thread-content-margin: 16px");
    expect(TOKENS).toContain("--radius-user-message: 22px");
    expect(TOKENS).toContain("--thread-content-max-width: 672px");
    expect(TOKENS).toContain("--thread-content-top-inset: 32px");
    expect(TOKENS).toContain("--sidebar-preferred-width: 275px");
    expect(CSS).toContain("--sidebar-width: clamp(240px, var(--sidebar-preferred-width), min(520px, calc(100vw - 320px)))");
    expect(TOKENS).toContain("--sidebar-scroll-fade-distance: 40px");
    expect(TOKENS).toContain("--height-toolbar: 46px");
    expect(TOKENS).toContain("--height-toolbar-sm: 36px");
    expect(TOKENS).toContain("--height-toolbar-pane: 40px");
    expect(TOKENS).toContain("--height-window-bar: var(--height-toolbar)");
    expect(TOKENS).toContain("--height-thread-toolbar: var(--height-window-bar)");
    expect(TOKENS).toContain("--height-file-toolbar: var(--height-toolbar-pane)");
    expect(TOKENS).toContain("--command-menu-width: 520px");
    expect(TOKENS).toContain("--command-menu-list-max-height: min(440px, max(120px, calc(90vh - 64px)))");
    expect(TOKENS).toContain("--radius-composer: 24px");
    expect(TOKENS).toContain("--size-composer-action: 28px");
    expect(TOKENS).toContain("--radius-composer-single-line: 22px");
    expect(TOKENS).toContain("--radius-composer-rail: 20px");
    expect(TOKENS).toContain("--height-composer-single-line: 44px");
    expect(TOKENS).toContain("--composer-multiline-input-min-height: 44px");
    expect(TOKENS).toContain("--composer-rail-inline-inset: 13px");
    expect(TOKENS).toContain("--composer-rail-tuck: 4px");
    expect(TOKENS).toContain("--shadow-composer: 0 0 0 1px rgba(0, 0, 0, .04)");
    expect(TOKENS).toContain("--shadow-composer: inset 0 0 1px rgba(255, 255, 255, .2)");
    expect(TOKENS).toContain("--surface-composer: #2a2a2a");
    expect(TOKENS).toContain("--surface-composer-action-bar: rgba(255, 255, 255, .08)");
    expect(TOKENS).toContain("--surface-user-message: color-mix(in oklab, var(--text-primary) 5%, transparent)");
    expect(TOKENS).toContain("--surface-overlay: #2d2d2d");
    expect(TOKENS).toContain("--surface-selected: #3c3638");
    expect(CSS).toContain(".state-chip.ready { color: var(--state-success); background: var(--state-success-surface); }");
    expect(CSS).toContain(".state-chip.attention { color: var(--state-attention); background: var(--state-attention-surface); }");
    expect(CSS).toContain("color: var(--state-danger); background: var(--state-danger-surface)");
    expect(CSS).not.toMatch(/\.theme-dark \.\S*(?:error|warning|attention|success|ready)[^{]*\{[^}]*(?:#[\da-f]{3,8}|rgba?\()/i);
    expect(CSS).not.toContain(".setup-logo");
    expect(TOKENS).toContain("--scrollbar-thumb-hover: var(--border-strong)");
    expect(TOKENS).toContain("--motion-basic: 150ms");
    expect(TOKENS).toContain("--motion-relaxed: 300ms");
    expect(TOKENS).toContain("--blur-lg: 16px");
    expect(TOKENS).toContain("--shadow-raised: 0 8px 16px -4px rgba(0, 0, 0, .12)");
    expect(TOKENS).toContain("--shadow-overlay: 0 16px 32px -8px rgba(0, 0, 0, .19)");
    expect(TOKENS).toContain("--ease-enter: cubic-bezier(.19, 1, .22, 1)");
    expect(TOKENS).toContain("--ease-exit: cubic-bezier(.8, 0, .4, 1)");
    expect(TOKENS).toContain("--ease-enter-snappy: cubic-bezier(.23, 1, .32, 1)");
    expect(CSS).toContain("@supports (corner-shape: superellipse(1.5))");
    expect(CSS).toContain("display: flex; background: var(--surface-canvas)");
    expect(CSS).toContain("--conversation-split: 352px");
    expect(CSS).toContain(".app-shell:has(.workspace-panel)");
    expect(CSS).toContain(".app-shell:has(.workspace-panel) { --height-active-thread-toolbar: var(--height-toolbar-pane); }");
    expect(CSS).toContain(".app-shell:has(.workspace-panel) .main-surface { flex-grow: 0; max-width: var(--conversation-split); }");
    expect(CSS).toContain(".panel-animated > [data-panel] { transition: flex-grow var(--motion-relaxed) var(--ease-basic), max-width var(--motion-relaxed) var(--ease-basic); }");
    expect(CSS).toContain(".panel-animated.panel-dragging > [data-panel] { transition: none; }");
    expect(CSS).toContain(".work-surface { min-width: 0; overflow: clip; }");
    expect(CSS).not.toContain(".work-surface { min-width: 0; overflow: hidden; }");
    expect(CSS).toContain(".workspace-resizer { position: absolute");
    expect(CSS).toContain(".artifact-preview-content { width: min(40rem, 100%)");
    expect(CSS).toContain("font-size: calc(var(--document-font-size) * 1.5)");
    expect(CSS).toContain("font-size: calc(var(--document-font-size) * 1.25)");
    expect(CSS).toContain(".artifact-preview-content blockquote");
    expect(CSS).toContain(".artifact-preview-content pre { max-height: none;");
    expect(CSS).toContain(".artifact-preview-content .document-code-block");
    expect(CSS).toContain(".result-markdown { font-size: var(--document-font-size); line-height: var(--document-leading); }");
    expect(CSS).toContain(".message:not(:first-child) { margin-top: var(--conversation-item-gap); }");
    expect(CSS).toContain(".result-markdown h1 { margin: 0 0 calc(var(--document-space) * 2);");
    expect(CSS).toContain(".assistant-message .result-markdown p { font-size: inherit; line-height: inherit; white-space: normal; }");
    expect(CSS).toContain(".artifact-workbench-toolbar { display: flex;");
    expect(CSS).toContain("padding: 0 8px 0 16px; border-bottom: 1px solid var(--border-subtle); background: var(--surface-canvas)");
    expect(CSS).toContain(".artifact-workbench-actions { justify-content: flex-end; }");
    expect(CSS).toContain(".artifact-workbench-notice { display: flex; align-items: center; gap: 6px;");
    expect(CSS).toContain(".artifact-row { display: grid; grid-template-columns: 28px minmax(0, 1fr) auto;");
    expect(CSS).toContain(".artifact-row:hover { background: var(--surface-hover); }");
    expect(CSS).toContain(".task-state-dot { position: relative; display: grid; place-items: center; width: 10px; height: 10px;");
    expect(CSS).toContain(".task-state-dot.active::after { position: absolute; inset: -1.25px;");
    expect(CSS).toContain(".turn-progress.attention .progress-goal-icon { color: var(--state-attention); }");
    expect(TOKENS).toContain("--composer-rail-indicator: color-mix(in srgb, var(--text-tertiary) 70%, transparent)");
    expect(CSS).toContain(".turn-progress-head { display: grid; grid-template-columns: 14px minmax(0, 1fr) auto auto;");
    expect(CSS).toContain(".progress-goal-icon { width: 14px; height: 14px; color: var(--composer-rail-indicator); }");
    expect(CSS).toContain(".workspace-tab { display: grid; grid-template-columns: minmax(0, 1fr) 22px; width: min(120px, 100%);");
    expect(CSS).toContain("min-height: var(--height-file-toolbar);");
    expect(CSS).toContain(".app-shell:has(.workspace-panel) .timeline { width: calc(100% - 20px); }");
    expect(CSS).toContain("grid-template-columns: minmax(0, 1fr); grid-template-rows: var(--height-active-thread-toolbar) minmax(0, 1fr)");
    expect(CSS).toContain(".workspace-panel { position: relative; flex: 1 1 auto; min-width: 0; max-width: calc(100% - var(--sidebar-width) - var(--conversation-split)); grid-template-rows: var(--height-toolbar-pane) 1fr;");
    expect(CSS).toContain(".workspace-resizer { position: absolute; z-index: 4; top: var(--height-active-thread-toolbar);");
    expect(CSS).toContain(".sidebar-resizer { position: absolute; z-index: 11; top: var(--height-toolbar-sm);");
    expect(CSS).toContain(".timeline { width: min(var(--thread-content-max-width), calc(100% - 48px));");
    expect(CSS).toContain("padding: var(--thread-content-top-inset) 0 174px;");
    expect(CSS).toContain(".navigation-collapsed > .sidebar { display: none; }");
    expect(CSS).toContain(".task-groups { display: grid; align-content: start; gap: 8px;");
    expect(CSS).toContain('.task-groups[data-fade-top="true"][data-fade-bottom="true"]');
    expect(CSS).toContain("calc(100% - var(--sidebar-scroll-fade-distance))");
    expect(CSS).toContain(".task-groups { -webkit-mask-image: none !important; mask-image: none !important; }");
    expect(CSS).toContain(".sidebar-footer { grid-template-columns: minmax(0, 1fr) 30px; align-items: center; gap: 2px; }");
    expect(CSS).toContain(".sidebar-footer > .ui-tooltip-anchor, .sidebar-footer > .ui-tooltip-anchor > .host-identity { width: 100%; }");
    expect(CSS).toContain(".host-identity { grid-template-columns: 18px minmax(0, 1fr) 8px;");
    expect(CSS).toContain(".sidebar-settings-button { display: grid; place-items: center; width: 30px; height: 30px;");
    expect(CSS).toContain(".environment-panel { position: absolute");
    expect(TOKENS).toContain("--thread-summary-panel-width: 300px");
    expect(TOKENS).toContain("--thread-summary-content-shift: -158px");
    expect(CSS).toContain(".environment-content { display: grid; gap: 7px; width: 100%; }");
    expect(CSS).toContain(".environment-section + .environment-section { padding-top: 7px; border-top: 1px solid var(--border-subtle); }");
    expect(CSS).toContain(".environment-row { display: grid; grid-template-columns: 18px minmax(0, 1fr) 14px; align-items: center; gap: 7px; min-height: 34px; }");
    expect(CSS).toContain("@keyframes environment-enter");
    expect(CSS).toContain("@keyframes workspace-content-enter");
    expect(CSS).not.toMatch(/:has\(\.environment-panel\)[^{]*\.work-surface\s*{[^}]*margin-right/);
    expect(CSS).toContain("@media (min-width: 1096px) and (max-width: 1535px)");
    expect(CSS).toContain(":is(.timeline, .composer-stack) { transform: translateX(var(--thread-summary-content-shift)); }");
    expect(CSS).toContain("width: min(var(--thread-content-max-width), calc(100% - 48px))");
    expect(CSS).toContain(".settings-workbench { display: grid; grid-template-columns: 164px minmax(0, 1fr)");
    expect(CSS).toContain(".settings-panel { min-width: 0; overflow: auto;");
    expect(CSS).toContain(".settings-navigation { display: flex;");
    expect(CSS).toContain(".home-suggestions { width: 100%; padding-top: 8px; pointer-events: auto; }");
    expect(CSS).not.toContain(".welcome-copy");
    expect(CSS).toContain(".new-work-surface .composer-wrap { top: clamp(210px, 27vh, 236px);");
    expect(CSS).toContain(".suggestion-grid button { position: relative; display: flex; align-items: center; gap: 6px; min-height: 40px;");
    expect(CSS).toContain(".suggestion-grid button:is(:hover, :focus-visible) { color: var(--text-primary); }");
    expect(CSS).toContain(".suggestion-grid button:active { transform: scale(.99); }");
    expect(CSS).toContain(".suggestion-grid .suggestion-icon svg { position: static;");
    expect(CSS).toContain(".suggestion-grid .suggestion-copy { min-width: 0; overflow: hidden; color: inherit; font-size: var(--text-sm); font-weight: 400; letter-spacing: normal; text-overflow: ellipsis; text-transform: none; white-space: nowrap; }");
    expect(CSS).not.toContain("grid-template-columns: 78px minmax(0, 1fr) 16px");
    expect(CSS).toContain(".new-work-surface .composer-wrap { top: 190px; }");
    expect(CSS).toContain(".setup-shell { position: relative; min-height: 100%; overflow: auto; padding: 46px 24px 64px; background: var(--surface-canvas);");
    expect(CSS).toContain(".setup-card { position: relative; width: min(39rem, 100%); margin: 0 auto;");
    expect(CSS).toContain(".setup-card::before { display: none; }");
    expect(CSS).toContain(".setup-grid { display: grid; grid-template-columns: 1fr 1fr;");
    expect(CSS).toContain(".setup-step { min-width: 0;");
    expect(CSS).toContain("@keyframes setup-step-enter");
    expect(CSS).toContain(".choice-options { display: grid; grid-template-columns: repeat(auto-fit, minmax(96px, 1fr));");
    expect(CSS).toContain('.choice-option[aria-pressed="true"]');
    expect(CSS).not.toContain(".field select");
    expect(CSS).toContain(".approval-card { display: grid; grid-template-columns: 24px minmax(0,1fr);");
    expect(CSS).toContain("border-left-color: var(--state-attention)");
    expect(CSS).toContain(".approval-foot { display: flex; align-items: center; justify-content: space-between;");
    expect(CSS).toContain(".workspace-sheet { display: grid; grid-template-rows: 48px 34px minmax(220px, 1fr) auto;");
    expect(CSS).toContain("width: min(620px, 100%)");
    expect(CSS).toContain(".workspace-entry { display: grid; grid-template-columns: minmax(0, 1fr) 34px;");
    expect(CSS).toContain(".entry-icon { display: grid; place-items: center; width: 24px; height: 24px; color: var(--text-tertiary); background: transparent;");
    expect(CSS).toContain(".command-filters { display: flex; gap: 2px;");
    expect(CSS).toContain(".command-filters button.selected { color: var(--text-primary); background: var(--surface-selected);");
    expect(CSS).not.toContain(".search-page");
    expect(CSS).toContain(".agents-heading { display: flex; align-items: end; justify-content: space-between; gap: 24px; padding: 40px 0 18px;");
    expect(CSS).toContain(".settings-heading { padding: 40px 0 18px; }");
    expect(CSS).toContain("grid-template-columns: 14px minmax(0, 1fr) auto auto");
    expect(CSS).toContain(".progress-state { color: var(--text-tertiary); font-size: var(--text-2xs); white-space: nowrap; }");
    expect(CSS).toContain(".topbar-actions .icon-button[aria-expanded=\"true\"] { color: var(--text-primary); background: transparent; }");
    expect(CSS).toContain(".topbar-text-action { display: flex; align-items: center; gap: 5px; height: 30px;");
    expect(CSS).toContain(".app-shell:has(.workspace-panel) .topbar-text-action { display: grid; place-items: center; width: 30px; padding: 0; }");
    expect(CSS).toContain(".ui-tooltip-anchor { position: relative; display: inline-flex; min-width: 0; }");
    expect(CSS).toContain("transition-delay: 350ms; font-size: var(--text-2xs);");
    expect(CSS).toContain(".ui-tooltip-anchor:focus-within > .ui-tooltip { transition-delay: 0ms; }");
    expect(CSS).toContain('.ui-tooltip-anchor:has(> button[aria-expanded="true"]) > .ui-tooltip { display: none; }');
    expect(CSS).toContain(".suggestion-grid > .ui-tooltip-anchor, .suggestion-grid > .ui-tooltip-anchor > button { width: 100%; }");
    expect(CSS).toContain(".suggestion-grid .ui-tooltip { white-space: normal; }");
    expect(CSS).toContain(".work-menu-trigger { display: grid; place-items: center; width: 24px; height: 24px;");
    expect(CSS).toContain(".desktop-action-menu { position: absolute; z-index: 12; top: 27px; left: 0; width: 220px;");
    expect(CSS).toContain(".command-center { grid-template-rows: auto minmax(0, 1fr); width: min(var(--command-menu-width), calc(100vw - 32px));");
    expect(CSS).toContain(".command-group > button { grid-template-columns: 20px minmax(0, 1fr) auto; gap: 8px; min-height: 32px;");
    expect(CSS).toContain(".command-scroll::-webkit-scrollbar { display: none; }");
    expect(CSS).toContain(".work-menu .desktop-action-menu { left: -4px; width: 204px; }");
    expect(CSS).toContain(".product-menu-status { display: grid; grid-template-columns: 18px minmax(0, 1fr) 8px;");
    expect(CSS).toContain("grid-template-columns: 18px minmax(0, 1fr) auto");
    expect(CSS).toContain(".user-message-bubble { position: relative; display: flex; max-width: var(--user-chat-width); min-width: 0; padding: 10px var(--thread-content-margin);");
    expect(CSS).not.toContain(".theme-dark .user-message > div");
    expect(CSS).toContain("background: var(--surface-user-message)");
    expect(CSS).toContain(".user-turn { display: flex; width: 100%; flex-direction: column; align-items: flex-end; gap: 4px;");
    expect(CSS).toContain(".user-message-content.collapsed { max-height: calc(19 * 1.55em); overflow: hidden; }");
    expect(CSS).toContain(".user-message-toggle { display: inline-flex; align-self: flex-start; align-items: center; gap: 4px; min-height: 20px; margin-top: 6px;");
    expect(CSS).toContain(".user-message-meta { display: flex; min-height: 20px; gap: 2px; opacity: 0;");
    expect(CSS).toContain(".user-message:hover .user-message-meta, .user-message:focus-within .user-message-meta { opacity: 1; }");
    expect(CSS).toContain(".result-meta { justify-content: flex-start; gap: 2px; min-height: 20px; margin-top: 6px;");
    expect(CSS).toContain("opacity: 0; transition: opacity var(--motion-basic) var(--ease-basic)");
    expect(CSS).toContain(".result-meta.attention { opacity: 1; }");
    expect(CSS).toContain(".turn-activity > summary { display: flex; align-items: center; gap: 6px;");
    expect(CSS).toContain(".turn-activity-body { display: grid; gap: 2px; margin-top: 4px; animation: turn-activity-enter 220ms");
    expect(CSS).toContain(".composer-stack { width: min(var(--thread-content-max-width), 100%); margin: 0 auto;");
    expect(CSS).toContain(".composer-rail { --composer-rail-transition-duration: var(--motion-relaxed);");
    expect(CSS).toContain("grid-template-rows: 1fr");
    expect(CSS).toContain('[data-composer-rail-item="exiting"] { grid-template-rows: 0fr;');
    expect(CSS).toContain("margin-inline: var(--composer-rail-inline-inset)");
    expect(CSS).toContain("border-radius: var(--radius-composer-rail) var(--radius-composer-rail) 0 0");
    expect(CSS).toContain("background: var(--surface-composer-action-bar)");
    expect(CSS).toContain(".composer-stack > .composer { width: 100%; margin: 0;");
    expect(CSS).toContain(".composer { width: min(var(--thread-content-max-width), 100%); border: 0; border-radius: var(--radius-composer);");
    expect(CSS).toContain("background: var(--surface-composer)");
    expect(CSS).toContain(".theme-dark .environment-panel, .theme-dark .environment-panel header");
    expect(CSS).toContain('.conversation-top-fade[data-visible="true"] { opacity: 1; }');
    expect(CSS).toContain(".conversation { overflow-anchor: none; }");
    expect(CSS).toContain("height: 16px; background: linear-gradient(to bottom, var(--surface-canvas), transparent)");
    expect(CSS).toContain(".conversation-tail-button { pointer-events: auto; position: absolute; z-index: 4; top: -25px; left: 50%;");
    expect(CSS).not.toContain(".conversation-tail-button { bottom:");
    expect(CSS).toContain("padding-left: 10px; padding-right: 0;");
    expect(CSS).toContain("box-shadow: var(--shadow-composer)");
    expect(CSS).toContain(".composer textarea { min-height: var(--composer-multiline-input-min-height); max-height: 25dvh; padding: 6px 12px 0;");
    expect(CSS).toContain(".composer-toolbar { min-height: var(--size-composer-action); padding: 0 8px 8px;");
    expect(CSS).toContain(".composer-tools { gap: 5px; }");
    expect(CSS).toContain(".composer { container: composer-footer / inline-size;");
    expect(CSS).toContain("@container composer-footer (width <= 440px)");
    expect(CSS).toContain("@container composer-footer (width <= 480px)");
    expect(CSS).toContain("html[data-client=\"desktop\"] .access-pill-label");
    expect(CSS).toContain("width: var(--size-composer-action); height: var(--size-composer-action);");
    expect(CSS).toContain('.composer[data-layout="single-line"] {');
    expect(CSS).toContain("grid-template-columns: auto minmax(0, 1fr) auto");
    expect(CSS).toContain("min-height: var(--height-composer-single-line)");
    expect(CSS).toContain("-webkit-backdrop-filter: blur(var(--blur-lg)); backdrop-filter: blur(var(--blur-lg))");
    expect(CSS).toContain("scrollbar-color: var(--scrollbar-thumb) transparent");
    expect(CSS).toContain("::-webkit-scrollbar-thumb");
    expect(CSS).toContain("background: var(--scrollbar-thumb-hover)");
  });
});

function media(query: string): string {
  const start = CSS.indexOf(`@media (${query})`);
  if (start < 0) throw new Error("missing media contract");
  const next = CSS.indexOf("\n@media ", start + 1);
  return CSS.slice(start, next < 0 ? undefined : next);
}

function contrast(foreground: string, background: string): number {
  const values = [foreground, background].map((hex) => {
    const channels = hex.match(/../g)?.map((value) => Number.parseInt(value, 16) / 255);
    if (!channels || channels.length !== 3) throw new Error("invalid color");
    const [red, green, blue] = channels.map((value) => value <= 0.04045
      ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4);
    return 0.2126 * red + 0.7152 * green + 0.0722 * blue;
  });
  return (Math.max(...values) + 0.05) / (Math.min(...values) + 0.05);
}
